'use client';
 
import React, { useState, useEffect } from 'react';
import Image from 'next/image';
import { MediaLibraryEntry } from '@/types';

export function ShowcaseGrid() {
    const [highlights, setHighlights] = useState<MediaLibraryEntry[]>([]);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        async function loadHighlights() {
            try {
                const res = await fetch('/api/media-library?mode=community');
                const json = await res.json();
                if (json.success) {
                    // Show up to 8 highlights
                    setHighlights(json.data.slice(0, 8));
                }
            } catch (err) {
                console.error('Failed to load community highlights:', err);
            } finally {
                setIsLoading(false);
            }
        }
        loadHighlights();
    }, []);

    return (
        <section className="py-32 px-6 relative overflow-hidden bg-[#0a0a0f]">
            <div className="max-w-7xl mx-auto space-y-16">
                <div className="flex flex-col md:flex-row justify-between items-end gap-8">
                    <div className="space-y-4">
                        <span className="text-[10px] font-black uppercase tracking-widest text-indigo-500">Global Synthesis</span>
                        <h2 className="text-4xl md:text-6xl font-black uppercase tracking-tighter text-white">Production <br />Highlights</h2>
                    </div>
                    <p className="text-slate-400 font-medium max-w-sm">
                        Every synthesis is a masterpiece. Explore the cinematic output generated by the Synthesis Studio community.
                    </p>
                </div>

                <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
                    {isLoading ? (
                        [...Array(4)].map((_, i) => (
                            <div key={i} className="aspect-[3/4] rounded-3xl bg-white/[0.02] border border-white/10 animate-pulse" />
                        ))
                    ) : highlights.length > 0 ? (
                        highlights.map((entry) => (
                            <div key={entry.id} className="aspect-[3/4] rounded-3xl bg-white/[0.02] border border-white/10 overflow-hidden relative group cursor-pointer">
                                <Image
                                    src={entry.url}
                                    alt={entry.prompt || 'Synthesis Highlight'}
                                    fill
                                    sizes="(max-width: 768px) 50vw, 25vw"
                                    className="object-cover opacity-80 group-hover:opacity-100 group-hover:scale-110 transition-all duration-700 grayscale group-hover:grayscale-0"
                                />
                                <div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent opacity-0 group-hover:opacity-80 transition-opacity" />
                                <div className="absolute bottom-6 left-6 right-6 opacity-0 group-hover:opacity-100 transition-all translate-y-4 group-hover:translate-y-0 duration-500">
                                    <div className="space-y-3">
                                        <div className="flex items-center gap-2">
                                            <div className="w-5 h-5 rounded-full bg-indigo-500/20 border border-indigo-500/40" />
                                            <span className="text-[9px] font-black uppercase tracking-widest text-white">
                                                {entry.metadata?.style || 'Senior Producer'}
                                            </span>
                                        </div>
                                        <p className="text-[10px] font-medium text-white/70 line-clamp-2 italic">
                                            &quot;{entry.prompt || 'Synthesis active...'}&quot;
                                        </p>
                                        <div className="flex gap-2">
                                            <button className="px-2 py-1 rounded-md bg-white/10 text-[8px] font-black uppercase text-white hover:bg-white/20 transition-colors">Clone</button>
                                            <button className="px-2 py-1 rounded-md bg-white/10 text-[8px] font-black uppercase text-white hover:bg-white/20 transition-colors">Inspect</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        ))
                    ) : (
                        <div className="col-span-full py-24 text-center text-slate-500 font-medium">
                            The Collective is currently synthesizing masterpieces.
                        </div>
                    )}
                </div>
            </div>
        </section>
    );
}
