import { IResearchStrategy, ResearchRequest, ResearchResult } from '../types';

export class MockStrategy implements IResearchStrategy {
    id = 'mock-engine';
    name = 'Mock Research Engine';

    async execute(req: ResearchRequest, onProgress: (message: string) => void): Promise<ResearchResult> {
        onProgress('Initializing simulated discovery...');
        await new Promise(resolve => setTimeout(resolve, 800));
        
        onProgress(`Searching for information about: ${req.topic}`);
        await new Promise(resolve => setTimeout(resolve, 1200));

        onProgress('Synthesizing facts and sources...');
        await new Promise(resolve => setTimeout(resolve, 800));

        return {
            sources: [
                {
                    id: 's1',
                    url: 'https://example.com/mock',
                    title: 'Mock Discovery Resource',
                    type: 'article',
                    credibilityScore: 95,
                    extractedContent: 'This is mock content found during a simulation.',
                    citations: ['Mock Fact 1']
                }
            ],
            facts: [
                {
                    id: 'f1',
                    statement: `${req.topic} is actually a very interesting subject for simulation.`,
                    sourceIds: ['s1'],
                    confidence: 99,
                    verified: true
                }
            ],
            outline: ['Introduction to Mockery', 'The Evolution of Simulator', 'Final Thoughts'],
            summary: `This is a simulated summary of research on ${req.topic}. It highlights the key findings and simulated insights generated by the Mock Strategy.`,
            logs: ['Job started', 'Mock searching complete', 'Mock synthesis complete']
        };
    }
}
