import {
    Loader2,
    Download,
    Trash2,
    Copy,
    Share2,
    Twitter,
    ExternalLink,
    MoreHorizontal,
    Heart,
    MessageSquare,
    Repeat,
    Flag,
    UserPlus,
    UserCheck,
    Trophy,
    ChevronLeft,
    ChevronRight,
    ChevronDown,
    Plus,
    Search,
    Settings,
    Image as ImageIcon,
    History,
    LayoutGrid,
    Layers,
    Check,
    X,
    AlertCircle,
    Clock,
    ArrowLeft,
    ArrowRight,
    Sparkles,
    Zap,
    CreditCard,
    LogOut,
    User,
    Home,
    Bell,
    Menu,
    Eye,
    EyeOff,
    Filter,
    Video,
    ArrowUp,
    ArrowDown,
    Info,
    Globe,
    HardDrive,
    AlertTriangle,
    Activity,
    Wand2,
    Shield,
    Upload,
    FileText,
    List,
    LayoutList,
    Users,
    Instagram,
    Rows,
    Tag,
    Play,
    Award,
    BookOpen
} from "lucide-react"

export const Icons = {
    play: Play,
    tag: Tag,
    instagram: Instagram,

    spinner: Loader2,
    users: Users,
    wand: Wand2,
    text: FileText,
    upload: Upload,
    download: Download,
    delete: Trash2,
    copy: Copy,
    share: Share2,
    twitter: Twitter,
    external: ExternalLink,
    more: MoreHorizontal,
    heart: Heart,
    comment: MessageSquare,
    variation: Repeat,
    report: Flag,
    follow: UserPlus,
    following: UserCheck,
    trophy: Trophy,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    plus: Plus,
    search: Search,
    settings: Settings,
    image: ImageIcon,
    history: History,
    grid: LayoutGrid,
    stack: Layers,
    check: Check,
    close: X,
    clock: Clock,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    sparkles: Sparkles,
    zap: Zap,
    billing: CreditCard,
    logout: LogOut,
    user: User,
    home: Home,
    bell: Bell,
    menu: Menu,
    eye: Eye,
    eyeOff: EyeOff,
    filter: Filter,
    video: Video,
    arrowUp: ArrowUp,
    arrowDown: ArrowDown,
    info: Info,
    globe: Globe,
    database: HardDrive,
    alert: AlertTriangle,
    activity: Activity,
    shield: Shield,
    error: AlertTriangle,
    list: List,
    feed: LayoutList,
    rows: Rows,
    exemplar: Award,
    bookOpen: BookOpen
}
